### ISSUE TITLE
ff_ffplay.c的completed状态

### ISSUE THREAD

**Issue by chriszeng87** [bbcallen/ijkplayer#151]
请教下master分支Android版里面ff_ffplay.c里的read_thread的compled的里有一句注释“it's a bit early to nofity complete here”，我测下来确实是这样，这个大概要怎么修复呢？能不能把注释下面的pause去掉？(我去掉了，暂没发现问题。。。)是不是应该在播放的线程里发出FFP_MSG_COMPLETED?这个近期会修复吗？

**Comment by bbcallen** [comment]
demux -> decoder -> output.
最好是在 output 端 post 这个message

近期暂时没有修复的计划。

**Comment by chriszeng87** [comment]
谢谢，但是我打印日志发现如果在这里暂停的话，会导致有最后有一些帧没播出来，暂停的操作是不是也要在output端最后播放完后再post一个消息回来呢？

**Comment by bbcallen** [comment]
是的，不过直接 ffp_toggle_pause() 就可以了，post 消息一般是用来把消息发到播放器外。

**Comment by chriszeng87** [comment]
找了一下下午，一直没找对地方，能告诉我在哪加比较好吧，如果是软解的话。。。
