### ISSUE TITLE
ijkplayer是否支持H.265，如果支持，编译的时候该如何配置？

### ISSUE THREAD

**Issue by swdrts** [bbcallen/ijkplayer#154]
ijkplayer是否支持H.265，如果支持，编译的时候该如何配置？谢谢……

**Comment by ctiao** [comment]
https://github.com/bbcallen/ijkplayer/issues/11

**Comment by flybird119** [comment]
265现在很多芯片都还不支持吧？如果用ffmpeg软解的话估计很难流畅。

**Comment by chodison** [comment]
在配置中添加这个，重新编译下ffmpeg。
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-decoder=hevc"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-decoder=vp9"

export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-demuxer=hevc"

export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-parser=vp9"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-parser=hevc"

**Comment by loveq369** [comment]
楼上用的是硬解码吗？

**Comment by swdrts** [comment]
试了下，目前版本H265， 720P播放还是比较流畅，1080P就有明显卡顿了，枭龙800处理器
