### ISSUE TITLE
MediaCodec测试的两个问题

### ISSUE THREAD

**Issue by jgfntu** [bbcallen/ijkplayer#157]
1、MI2S上测试MediaCodec由硬解码切换到软解码时，画面卡住不动的问题（另外一部S4正常）
01-21 21:07:02.854: E/IJKMEDIA(22104): SDL_Android_NativeWindow_display_l: unknown hal format: 2141391875
01-21 21:07:02.934: E/IJKMEDIA(22104): SDL_Android_NativeWindow_display_l: unknown hal format: 2141391875
01-21 21:07:03.014: E/IJKMEDIA(22104): SDL_Android_NativeWindow_display_l: unknown hal format: 2141391875
01-21 21:07:03.055: E/IJKMEDIA(22104): SDL_Android_NativeWindow_display_l: unknown hal format: 2141391875
01-21 21:07:03.085: E/IJKMEDIA(22104): SDL_Android_NativeWindow_display_l: unknown hal format: 2141391875
01-21 21:07:03.135: E/IJKMEDIA(22104): SDL_Android_NativeWindow_display_l: unknown hal format: 2141391875
01-21 21:07:03.175: E/IJKMEDIA(22104): SDL_Android_NativeWindow_display_l: unknown hal format: 2141391875
01-21 21:07:03.215: E/IJKMEDIA(22104): SDL_Android_NativeWindow_display_l: unknown hal format: 2141391875

跟踪了下代码，是SDL_Android_NativeWindow_display_l()函数里面报出的错误，get回来的format不对导致的
    int curr_format = ANativeWindow_getFormat(native_window);
    int buff_w = IJKALIGN(overlay->w, 2);
    int buff_h = IJKALIGN(overlay->h, 2);

    AndroidHalFourccDescriptor *voutDesc = native_window_get_desc(curr_format);
    if (!voutDesc) {
        ALOGE("SDL_Android_NativeWindow_display_l: unknown hal format: %d", curr_format);
        return -1;
    }

2、概率性出现启用mediacodec失败的问题（MI2S和S4都遇到了）
     01-20 17:20:59.136: I/tv.danmaku.ijk.media.player.IjkMediaPlayer(15816): selected codec: OMX.Exynos.AVC.Decoder rank=700
     01-20 17:20:59.136: I/ACodec(15816):  [] Now uninitialized
     01-20 17:20:59.136: I/OMXClient(15816): Using client-side OMX mux.
     01-20 17:20:59.151: I/ACodec(15816): [OMX.Exynos.AVC.Decoder] Now Loaded
     01-20 17:20:59.151: E/MediaCodec(15816): native_window_api_connect returned an error: Invalid argument (-22)
     01-20 17:20:59.151: W/System.err(15816): java.lang.IllegalStateException
     01-20 17:20:59.151: W/System.err(15816):      at android.media.MediaCodec.native_configure(Native Method)
     01-20 17:20:59.156: W/System.err(15816):      at android.media.MediaCodec.configure(MediaCodec.java:262)
     01-20 17:20:59.156: W/System.err(15816):      at dalvik.system.NativeStart.run(Native Method)
     01-20 17:20:59.156: I/ACodec(15816):  [OMX.Exynos.AVC.Decoder] Now uninitialized

**Comment by bbcallen** [comment]
第一个问题试试这个提交。
https://github.com/bbcallen/ijkplayer/commit/71c190638210f7a861266e08866a3ef982241d97

第二个问题需要更多的重现条件。

**Comment by jgfntu** [comment]
第一个问题修改后的提交是不行的，signall-11的错误，signal的具体栈日志系统没打印出来。我调试了几次，发现可能跟java层传递下去的surfaceHolder有关系，因为从硬解码切换到软解码的时候，surface我没有重新创建，还是MediaCodec播放时候的surface，然后ANativeWindow_getFormat(native_window)回来的format是一个奇怪的值0x7FA30C03，但是如果我切换的时候将surfaceview先gone再visible一下就正常了，返回的就是我设置的SDL_RV32相对应的format值：HAL_PIXEL_FORMAT_RGBX_8888。
同时，看到这个现象，我产生了点疑问，java层调用setOverlayFormat(AvFourCC.SDL_FCC_XXX)设置对应格式，然后_setVideoSurface， ANativeWindow_fromSurface拿到native_window，然后ANativeWindow_getFormat的格式是怎么对应上的，纯软解的时候，我设置不同SDL_FCC_XXX，get回来的基本都能对应上，很少需要ANativeWindow_setBuffersGeometry，代码里面我没找到对应的地方，另外，之前用vlc的时候，设置了mSurfaceHolder.setFormat(xxx)参数的，ijk里面好像没有设置，并且设置了反而不对了

**Comment by bbcallen** [comment]
#153

**Comment by jgfntu** [comment]
跟#153的问题确实很类似。修改过后的代码确实可以了，是不是ANativeWindow_setBuffersGeometry纠正过之后先return，然后再SDL_Android_NativeWindow_display_l之后就获取到了正确的format，效果上和surfaceView reset了一次效果是相同的

**Comment by bbcallen** [comment]
是的

**Comment by jgfntu** [comment]
第二个问题应该也是类似的原因，从软解码切换到mediaCodec初始化配置时，surface也出了问题，暂时先reset了surfaceview来解决的

**Comment by qqli007** [comment]
@jgfntu ,怎么reset surfaceview？我这边使用textureview播放视频，也出现了第二个问题，不知道怎么解决
