### ISSUE TITLE
[QUESTION] Hardware Acceleration (why disabled by default?)

### ISSUE THREAD

**Issue by stuckless** [bbcallen/ijkplayer#162]
I noticed in the ```config/module-default.sh``` that the hardware acceleration is disabled.  I'm wondering if this is a requirement (ie, for h264 videos, I'd like to use hardware acceleration if possible).

I know nothing about video encoding/decoding and/or ffmpeg internals, but if I enabled the  hardware acceleration, would the VideoView auto-detect and use hardware acceleration?  or would custom coding be required to make this work.

```
# Hardware accelerators:
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --disable-dxva2"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --disable-vaapi"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --disable-vda"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --disable-vdpau"

# Individual component options:
# export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --disable-everything"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --disable-encoders"
# export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --disable-decoders"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --disable-hwaccels"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --disable-muxers"
# export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --disable-demuxers"
# export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --disable-parsers"
# export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --disable-bsfs"
# export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --disable-protocols"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --disable-devices"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --disable-filters"
```

Thanks,

**Comment by xqq** [comment]
HW accelerators in FFmpeg doesn't support ios/android, so these are useless in ijkplayer.
dxva2(for Windows), vaapi(for Linux), vda(for OSX), vdpau(for Linux NVIDIA) are for desktop OS.
For Android, hardware decoding depends on MediaCodec API, ijkplayer has implemented it while FFmpeg doesn't support yet.

**Comment by stuckless** [comment]
@xqq So if I understand you correctly, ijkplayer would already have support for hardware decoding based on MediaCodec API... so do I need to do anything to "enable" it or would the ijkmediaplayer automatically determine when to use it?  Thanks.

**Comment by xqq** [comment]
@stuckless 
https://github.com/bbcallen/ijkplayer/blob/master/android/ijkmediaplayer/src/tv/danmaku/ijk/media/player/IjkMediaPlayer.java

Only call setMediaCodecEnabled(true);

**Comment by stuckless** [comment]
@xqq I will try it out... thanks.

**Comment by jerrylin1002** [comment]
Hello...can you help me how to call "setMediaCodecEnabled(true)" to enable the hardware acceleration please?

**Comment by stuckless** [comment]
I just wanted to update this, since I think the new way to enable Hardware Acceleration is to use

```
ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "mediacodec", 1);
```
