### ISSUE TITLE
如何改变视频的清晰度呢？

### ISSUE THREAD

**Issue by xhzengAIB** [bbcallen/ijkplayer#163]
Hi! @bbcallen 

同一个live视频源，在iOS与在Android上的清晰度都不一样，请问这个是原因导致的呢？

Jack

**Comment by xhzengAIB** [comment]
需要配置什么吗？还是需要设置某个参数

**Comment by bbcallen** [comment]
有日志么?

**Comment by xhzengAIB** [comment]
你好！ 因为我是看安卓上的视频比iOS上的清晰，没有注意日志，我以为是可以通过参数配置视频的清晰度的呢！

客户端的直播整个过程，在哪些环节会出现压缩视频的呢？

我不知道拿什么日志给你看啊！

**Comment by bbcallen** [comment]
默认没有压缩视频的流程。

**Comment by xhzengAIB** [comment]
但是为什么，同样的代码在iOS和安卓上是不一样的呢？

**Comment by xhzengAIB** [comment]
因为在清晰度上有比较明显的差别

**Comment by bbcallen** [comment]
不知道，信息太少，无法判断。

**Comment by chodison** [comment]
多提供些信息，如片源地址。

**Comment by jinlking** [comment]
我们这边一样的问题  IOS和android播放同样的视频源，IOS当运动的时候脸部明显出现锯齿和模糊，特别是运动的时候。
同样的源用kxmoviex就不会有问题。

**Comment by jinlking** [comment]
我试着把kxmovie的render移植过来，发现效果一样，应该不是显示的问题，都是RGB输出，同样的源，kxmovie是好的，ijkplayer就会有问题

**Comment by bbcallen** [comment]
如果文件里有多个视频流，ijkplayer会随便选择一个，而不是清晰度最高。
没有日志的话，我无法判断你是不是这种情况。

**Comment by jinlking** [comment]
@bbcallen  发邮件到你邮箱了 截图和原始视频。

**Comment by jinlking** [comment]
android 和  IOS都有问题，都不清晰。

**Comment by jinlking** [comment]
OK 知道到原因了，设置了报丢弃，改成不丢就ok了。

**Comment by bbcallen** [comment]
好吧，我以为默认是没有设的。。。

**Comment by xhzengAIB** [comment]
@jinlking 
怎么设置？

**Comment by gf589462** [comment]
@bbcallen 你好：
     我想请教一下使用，kxmovie的时候怎么去停止播放啊，我看了源码，没太看懂。他这个只是在dealloc和WillDisAppear中暂停了，这样造成我进入多个视频，会内存暴涨。

**Comment by allentsing** [comment]
@jinlking 你说的设置报丢弃是怎么设置的？
