### ISSUE TITLE
Mute audio in video

### ISSUE THREAD

**Issue by erema** [bbcallen/ijkplayer#173]
I want to mute/unmute sound in video, how can I do that?

**Comment by bbcallen** [comment]
Not support yet. you can set volume to 0, for now.

**Comment by erema** [comment]
Thanks for fast answer. But, setVolume for iOS doesn't work unfortunately.

**Comment by bbcallen** [comment]
use [MPMusicPlayerController applicationMusicPlayer].volume;

**Comment by erema** [comment]
thank you. What about looping. I try to loop video and in the end of video I see a black screen for 1 second, how can I fix it?
