### ISSUE TITLE
URLs are truncated to 1024 bytes

### ISSUE THREAD

**Issue by waninkoko** [bbcallen/ijkplayer#174]
I'm trying to play a video which URL is very long. After checking Ijkplayer refused to play it, I started to investigate and found out that FFmpeg is trying to open the URL but truncated to 1024 bytes

I took a quick look at Ijkplayer to find where is the problem but I didn't have any luck. I also checked if the problem was FFmpeg but they have specified a limit of 4096 bytes for URLs (MAX_URL_SIZE constant).

**Comment by waninkoko** [comment]
Issue found and fixed in this commit:

https://github.com/lowlevel-studios/ijkplayer/commit/0caee9da9f85b476e367c417a0f03c3de532e88b

**Comment by bbcallen** [comment]
Merged, thanks
