### ISSUE TITLE
How to output frames as they are decoded (no drops and no duplicates)?

### ISSUE THREAD

**Issue by kalyazin** [bbcallen/ijkplayer#177]
I am looking for something close to vsync = passthrough in ffmpeg and re in ffplay.
What I need is to output all decoded frames at decoding rate (not in frame rate described in the videostream).
Is that possible in ijkplayer?

**Comment by bbcallen** [comment]
I guess ijkplayer is a little overhead for that. Try the ffmpeg official example:
http://git.videolan.org/?p=ffmpeg.git;a=blob;f=doc/examples/demuxing_decoding.c;h=feeeb967f82e71e76fb4724010547133b827f143;hb=HEAD

**Comment by kalyazin** [comment]
Thank you for the reply.
I achieved what I needed with removing the following line (VideoView.java):
ijkMediaPlayer.setFrameDrop(12);
