### ISSUE TITLE
Hardware Acceleration

### ISSUE THREAD

**Issue by jerrylin1002** [bbcallen/ijkplayer#185]
Hello, 

  I browsed over and over, and found this issue was solved earlier this year @ https://github.com/bbcallen/ijkplayer/issues/162

  Can you advise me how to call "setMediaCodecEnable" to enable the hardware acceleration please? Thanks so much!!

**Comment by bbcallen** [comment]
```
mp.setMediaCodecEnable(true);
```

**Comment by jerrylin1002** [comment]
at ijkmediaplayerdemo's VideoPlayerActivity.java, it's called by VideoView on the widget. Please advise how to make "mVideoView.setMediaCodecEnabled(true)" work?

**Comment by bbcallen** [comment]
Modify it by yourself.
VideoView.java is only a demo.

**Comment by jerrylin1002** [comment]
I studied your codes just a little while; and no idea how to make changes on VideoView.java for enabling this feature. Please kindly advise. Thanks in advance
