### ISSUE TITLE
build on Linux x86_64 Host system 'linux-x86' is not supported by the source NDK! Try --system=<name> with one of:  darwin-x86_64

### ISSUE THREAD

**Issue by 4kr4m** [bbcallen/ijkplayer#207]
I'm using ubuntu 14.10 
ndk r9 64x

can't figure out the problem. any help ?

**Comment by bbcallen** [comment]
darwin-x86_64 is for Mac OS, Maybe you've downloaded wrong ndk,

**Comment by 4kr4m** [comment]
that was right. i really appreciate your answer
