### ISSUE TITLE
RTSP protocol not found

### ISSUE THREAD

**Issue by vinceycy** [bbcallen/ijkplayer#208]
Good day,

ijkplayer支援rtsp的串流嗎？使用後回傳了"Protocol not found"錯誤，還需要調整什麼嗎？我是直接使用demo code裡的VideoView播放

**Comment by bbcallen** [comment]
https://github.com/bbcallen/ijkplayer/issues/136

**Comment by vinceycy** [comment]
Thanks,

有照步驟更改過，不過還是一樣，是Android的，我再試看看，有解決會再PO上來。如果還有什麼需要更改的再麻煩指教一下。

**Comment by vinceycy** [comment]
rtsp://184.72.239.149/vod/mp4:BigBuckBunny_175k.mov
串流來源是這個

**Comment by vinceycy** [comment]
可以播了

我使用module-default.sh來取代module-lite.sh，並把module.sh刪除，然後從./init-android.sh步驟開始

感謝作者的回覆

**Comment by 10045125** [comment]
如果需要编解码swf的flash，需要做哪些东西呢，我试了楼上的方法，还是不行，结果提示
could not find codec parameters

**Comment by vinceycy** [comment]
沒試過swf的，應該是沒有它的codec可用，看要不要轉成其它檔試試

**Comment by 10045125** [comment]
FFmpeg 官方上说是支持SWF，如果有SWF的codec ，需要如何加入呢？

**Comment by bbcallen** [comment]
用 module-default.sh 取代 module-lite.sh

**Comment by 10045125** [comment]
我是用module-default.sh的，编译出来的大概有7M，结果还是不能编解码swf，感觉这个开源项目特别棒，android 4.1 webview貌似不支持swf ，如果能加入swf，我觉得是一个很棒的东西。

**Comment by bbcallen** [comment]
你先试试装个 ffplay 或者 vlc 试着播一下。
如果 ffplay 不支持的话，那么 ijkplayer 也不支持。

**Comment by TianLuhua** [comment]
这个问题都过去两年了，不知道怎么样了。现在公司也需要播放SWF，ijk助我。
